"""empty message

Revision ID: 30be82fa8afa
Revises: 8f7d6e317c16
Create Date: 2024-03-12 16:24:15.346556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30be82fa8afa'
down_revision = '8f7d6e317c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
